### ISSUE TITLE
[BUG] - incompatible freesasa version with python 3.12 (see #13)

### ISSUE THREAD

**Issue by nchenche** [i2bc/SURFMAP#14]
## Description

Install of surfmap won't work with python 3.12 because of freesasa 2.1.0 incompatible

## Command 

`python -m pip install --use-pep517 -e git+https://github.com/i2bc/SURFMAP.git@v2.0.0#egg=surfmap`

## Error 
```bash
...
clang -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /Users/atanasradkov/opt/anaconda3/envs/surfmap/include -fPIC -O2 -isystem /Users/atanasradkov/opt/anaconda3/envs/surfmap/include -Ilib/src -I. -I/Users/atanasradkov/opt/anaconda3/envs/surfmap/include/python3.12 -c src/freesasa.c -o build/temp.macosx-10.9-x86_64-cpython-312/src/freesasa.o -DHAVE_CONFIG_H -std=gnu99
src/freesasa.c:236:12: fatal error: 'longintrepr.h' file not found
#include "longintrepr.h"
^~~~~~~~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for freesasa
Successfully built surfmap
Failed to build freesasa
ERROR: Could not build wheels for freesasa, which is required to install pyproject.toml-based projects
```

## Solution

Change freesasa version in setup.py file: from 2.1.0 to 2.2.1
